(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const els={client:$('#clientFilter'),product:$('#productFilter'),status:$('#statusFilter'),updated:$('#updatedAt'),liveBadge:$('#liveBadge'),liveText:$('#liveText'),connectionDot:$('#connectionDot'),connectionTitle:$('#connectionTitle'),connectionSub:$('#connectionSub'),hero:$('#heroAlert'),heroTitle:$('#heroAlertTitle'),heroText:$('#heroAlertText'),heroRisk:$('#heroRisk'),actual:$('#kpiActual'),suggested:$('#kpiSuggested'),excess:$('#kpiExcess'),excessFoot:$('#kpiExcessFoot'),returns:$('#kpiReturns'),returnsFoot:$('#kpiReturnsFoot'),weeks:$('#kpiWeeksAbove'),finalStock:$('#kpiFinalStock'),chart:$('#comparisonChart'),nextOrder:$('#nextOrderCard'),excessSummary:$('#excessSummary'),table:$('#weeklyTable'),clientsList:$('#clientsList'),productsList:$('#productsList'),alertsList:$('#alertsList'),alertsCount:$('#activeAlertsCount'),modal:$('#connectionModal'),url:$('#apiUrlInput'),key:$('#apiKeyInput'),interval:$('#refreshIntervalInput'),previewDot:$('#connectionPreviewDot'),previewTitle:$('#connectionPreviewTitle'),previewText:$('#connectionPreviewText'),drawer:$('#detailDrawer'),drawerBack:$('#detailDrawerBackdrop'),drawerTitle:$('#drawerTitle'),drawerContent:$('#drawerContent')};
let dataset=window.DEMO_DASHBOARD_DATA||{rows:[]}, timer=null;
const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(Number(n)||0);
const pct=n=>new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1}).format(Number(n)||0);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function n(v){if(typeof v==='number')return Number.isFinite(v)?v:0;if(v==null||v==='')return 0;let s=String(v).trim().replace(/\s/g,'');if(/^\d{1,3}(\.\d{3})*,\d+$/.test(s))return Number(s.replace(/\./g,'').replace(',','.'))||0;return Number(s.replace(',','.'))||0}
function normalize(raw){const a=Array.isArray(raw)?raw:Array.isArray(raw?.rows)?raw.rows:[];return a.map(r=>({cliente:r.cliente??r.Cliente??'Não informado',produto:r.produto??r.Produto??'Não informado',semana:r.semana??r.Semana??'',estoqueAtual:n(r.estoqueAtual??r['Estoque Atual']),trocas:n(r.trocas??r['Trocas/Devoluções']),vendas:n(r.vendas??r['Vendas Cliente']),estoqueMinimo:n(r.estoqueMinimo??r['Estoque Mínimo']),estoqueMaximo:n(r.estoqueMaximo??r['Estoque Máximo']),sugestao:n(r.sugestao??r['Sugestão Reposição']),reposicaoReal:n(r.reposicaoReal??r['Reposição Real']),estoqueFinal:n(r.estoqueFinal??r['Estoque Final']),taxaTrocas:n(r.taxaTrocas??r['Taxa Trocas']),excesso:n(r.excesso??r['Excesso vs Sugestão']),diferencaPct:n(r.diferencaPct??r['Diferença %']),status:String(r.status??r.Status??'OK').toUpperCase(),risco:String(r.risco??r.Risco??'NORMAL').toUpperCase()})).filter(x=>x.semana)}
function config(){return{url:localStorage.getItem('rp_api_url')||'',key:localStorage.getItem('rp_api_key')||'',interval:Number(localStorage.getItem('rp_refresh')||30000)}}
function fillFilters(){const rows=normalize(dataset);const oldC=els.client.value,oldP=els.product.value;const clients=[...new Set(rows.map(r=>r.cliente))].sort();els.client.innerHTML='<option value="__all">Todos os clientes</option>'+clients.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');els.client.value=clients.includes(oldC)?oldC:(clients.length===1?clients[0]:'__all');fillProducts(oldP)}
function fillProducts(old){const rows=normalize(dataset).filter(r=>els.client.value==='__all'||r.cliente===els.client.value);const products=[...new Set(rows.map(r=>r.produto))].sort();els.product.innerHTML='<option value="__all">Todos os produtos</option>'+products.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');els.product.value=products.includes(old)?old:(products.length===1?products[0]:'__all')}
function selectedRows(){return normalize(dataset).filter(r=>(els.client.value==='__all'||r.cliente===els.client.value)&&(els.product.value==='__all'||r.produto===els.product.value)&&(els.status.value==='__all'||r.status===els.status.value))}
function allRows(){return normalize(dataset)}
function aggregate(rows,key){const m=new Map();for(const r of rows){const k=r[key]||'Não informado';if(!m.has(k))m.set(k,{name:k,rows:[],actual:0,suggested:0,excess:0,returns:0,sales:0});const a=m.get(k);a.rows.push(r);a.actual+=r.reposicaoReal;a.suggested+=r.sugestao;a.excess+=r.excesso;a.returns+=r.trocas;a.sales+=r.vendas}return [...m.values()].map(a=>({...a,returnRate:(a.sales+a.returns)>0?a.returns/(a.sales+a.returns):0,above:a.rows.filter(r=>r.status==='ACIMA').length}))}
function render(){const rows=selectedRows();renderOverview(rows);renderClients();renderProducts();renderAlerts();els.updated.textContent=formatDate(dataset.updatedAt||new Date().toISOString())}
function renderOverview(rows){const sum=k=>rows.reduce((t,r)=>t+(r[k]||0),0), actual=sum('reposicaoReal'), suggested=sum('sugestao'), excess=sum('excesso'), returns=sum('trocas'), sales=sum('vendas'), rate=(sales+returns)>0?returns/(sales+returns):0, above=rows.filter(r=>r.status==='ACIMA').length,last=rows[rows.length-1];els.actual.textContent=fmt(actual);els.suggested.textContent=fmt(suggested);els.excess.textContent=fmt(excess);els.excessFoot.textContent=actual?`${pct(excess/actual)} do que foi pedido`:'acima da sugestão';els.returns.textContent=fmt(returns);els.returnsFoot.textContent=`${pct(rate)} da movimentação`;els.weeks.textContent=`${above}/${rows.length}`;els.finalStock.textContent=last?fmt(last.estoqueFinal):'—';renderHero(rows,excess,actual,rate);renderChart(rows);renderNext(rows);renderExcess(rows,excess,actual);renderTable(rows)}
function renderHero(rows,excess,actual,rate){const high=rows.some(r=>r.risco==='ALTO')||rate>=.06, att=rows.some(r=>r.risco==='ATENÇÃO')||rows.some(r=>r.status==='ACIMA');els.hero.className='hero-alert '+(high?'danger':(!att?'good':''));if(!rows.length){els.heroTitle.textContent='Nenhum dado para o filtro atual';els.heroText.textContent='Altere os filtros para visualizar outra combinação.';els.heroRisk.textContent='SEM DADOS';return}if(high){els.heroTitle.textContent='Há risco elevado de perda por excesso';els.heroText.textContent=`O período reúne ${fmt(excess)} unidades acima da sugestão e taxa de trocas de ${pct(rate)}.`;els.heroRisk.textContent='RISCO ALTO'}else if(att){els.heroTitle.textContent='Há pedidos que merecem revisão';els.heroText.textContent=`O excesso potencial acumulado é de ${fmt(excess)} unidades${actual?` (${pct(excess/actual)} do pedido realizado)`:''}.`;els.heroRisk.textContent='ATENÇÃO'}else{els.heroTitle.textContent='Reposição dentro do padrão';els.heroText.textContent=`Os pedidos estão próximos da sugestão. Taxa de trocas estimada: ${pct(rate)}.`;els.heroRisk.textContent='CONTROLADO'}}
function renderChart(rows){if(!rows.length){els.chart.innerHTML='<div class="empty-state">Sem dados para o gráfico.</div>';return}const max=Math.max(1,...rows.flatMap(r=>[r.sugestao,r.reposicaoReal]));els.chart.innerHTML=rows.map(r=>`<div class="chart-col" title="${esc(r.semana)} · Sugerido ${fmt(r.sugestao)} · Realizado ${fmt(r.reposicaoReal)}"><div class="bars"><div class="bar suggested" style="height:${Math.max(3,r.sugestao/max*100)}%"></div><div class="bar actual ${r.status==='ACIMA'?'over':''}" style="height:${Math.max(3,r.reposicaoReal/max*100)}%"></div></div><div class="bar-label">${esc(String(r.semana).replace('Semana ','S'))}</div></div>`).join('')}
function renderNext(rows){if(!rows.length){els.nextOrder.innerHTML='<div class="empty-state">Sem dados.</div>';return}const r=rows[rows.length-1], limit=Math.max(0,Math.round(r.sugestao)), final=Math.max(0,Math.round(r.estoqueFinal));els.nextOrder.innerHTML=`<div class="big">${fmt(limit)}</div><div class="unit">unidades sugeridas como referência</div><div class="rule"></div><div class="mini-grid"><div class="mini-card"><span>Estoque final</span><b>${fmt(final)}</b></div><div class="mini-card"><span>Último pedido</span><b>${fmt(r.reposicaoReal)}</b></div></div><div class="callout" style="background:${r.reposicaoReal>r.sugestao?'var(--red-soft)':'var(--green-soft)'};color:${r.reposicaoReal>r.sugestao?'#8f2f35':'#0c684b'}">${r.reposicaoReal>r.sugestao?`Último pedido ficou ${fmt(r.reposicaoReal-r.sugestao)} un. acima da sugestão.`:`Último pedido ficou dentro ou abaixo da sugestão calculada.`}</div>`}
function renderExcess(rows,excess,actual){const max=Math.max(1,...rows.map(r=>r.excesso)), worst=[...rows].sort((a,b)=>b.excesso-a.excesso)[0];els.excessSummary.innerHTML=`<div class="big-number">${fmt(excess)} <small>unidades</small></div><div class="progress-block"><div class="progress-label"><span>Excesso sobre o pedido</span><b>${actual?pct(excess/actual):'0%'}</b></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,actual?excess/actual*100:0)}%"></div></div></div>${worst?`<div class="callout">Maior excesso: <b>${esc(worst.semana)}</b>, com ${fmt(worst.excesso)} un. acima do recomendado.</div>`:''}`}
function renderTable(rows){els.table.innerHTML=rows.length?rows.map((r,i)=>`<tr data-row="${i}"><td><b>${esc(r.semana)}</b></td><td>${fmt(r.estoqueAtual)}</td><td>${fmt(r.vendas)}</td><td>${fmt(r.trocas)}</td><td><b>${fmt(r.sugestao)}</b></td><td><b>${fmt(r.reposicaoReal)}</b></td><td>${fmt(r.excesso)}</td><td><span class="status ${r.status==='ACIMA'?'above':r.status==='ABAIXO'?'below':'ok'}">${esc(r.status)}</span></td><td><span class="risk ${r.risco==='ALTO'?'high':r.risco==='ATENÇÃO'?'attention':'normal'}">${esc(r.risco)}</span></td></tr>`).join(''):'<tr><td colspan="9"><div class="empty-state">Nenhum dado encontrado.</div></td></tr>';$$('#weeklyTable tr[data-row]').forEach(tr=>tr.addEventListener('click',()=>openRowDetail(rows[Number(tr.dataset.row)])))}
function renderClients(){let list=aggregate(allRows(),'cliente');const q=($('#clientSearch')?.value||'').toLowerCase(),sort=$('#clientSort')?.value||'excess';list=list.filter(x=>x.name.toLowerCase().includes(q)).sort((a,b)=>sort==='returns'?b.returnRate-a.returnRate:sort==='actual'?b.actual-a.actual:b.excess-a.excess);els.clientsList.innerHTML=list.length?list.map(x=>entityRow(x,'cliente')).join(''):'<div class="empty-state">Nenhum cliente encontrado.</div>'}
function renderProducts(){let list=aggregate(allRows(),'produto');const q=($('#productSearch')?.value||'').toLowerCase(),sort=$('#productSort')?.value||'excess';list=list.filter(x=>x.name.toLowerCase().includes(q)).sort((a,b)=>sort==='returns'?b.returnRate-a.returnRate:sort==='actual'?b.actual-a.actual:b.excess-a.excess);els.productsList.innerHTML=list.length?list.map(x=>entityRow(x,'produto')).join(''):'<div class="empty-state">Nenhum produto encontrado.</div>'}
function entityRow(x,type){const risk=x.excess>0||x.returnRate>.04?'ATENÇÃO':'NORMAL';return `<div class="entity-row"><div class="entity-name"><b>${esc(x.name)}</b><small>${x.rows.length} registros analisados</small></div><div class="entity-metric"><span>Reposição</span><b>${fmt(x.actual)}</b></div><div class="entity-metric"><span>Sugerido</span><b>${fmt(x.suggested)}</b></div><div class="entity-metric"><span>Excesso</span><b>${fmt(x.excess)}</b></div><div class="entity-metric hide-md"><span>Trocas</span><b>${pct(x.returnRate)}</b></div><div><span class="risk ${risk==='ATENÇÃO'?'attention':'normal'}">${risk}</span></div></div>`}
function renderAlerts(){const rows=allRows(), alerts=[];for(const r of rows){if(r.status==='ACIMA'&&r.excesso>0)alerts.push({level:r.risco==='ALTO'?'high':'attention',title:`Pedido acima da sugestão · ${r.semana}`,text:`${r.cliente} · ${r.produto}: pedido de ${fmt(r.reposicaoReal)} un., contra ${fmt(r.sugestao)} sugeridas. Excesso de ${fmt(r.excesso)} un.`,meta:r.risco});if(r.taxaTrocas>.045)alerts.push({level:'high',title:`Trocas elevadas · ${r.semana}`,text:`${r.cliente} · ${r.produto}: taxa de trocas em ${pct(r.taxaTrocas)}.`,meta:'TROCAS'});if(r.status==='ABAIXO'&&r.reposicaoReal<r.sugestao*.8)alerts.push({level:'low',title:`Pedido abaixo da sugestão · ${r.semana}`,text:`${r.cliente} · ${r.produto}: realizado ${fmt(r.reposicaoReal)} un. contra ${fmt(r.sugestao)} sugeridas.`,meta:'ABAIXO'})}els.alertsCount.textContent=alerts.length;els.alertsList.innerHTML=alerts.length?alerts.map(a=>`<article class="alert-item ${a.level}"><div class="alert-icon-sm">!</div><div><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p></div><div class="alert-meta"><b>${esc(a.meta)}</b>revisar</div></article>`).join(''):'<div class="panel"><div class="empty-state">Nenhum alerta ativo nos dados atuais.</div></div>'}
function openRowDetail(r){els.drawerTitle.textContent=r.semana;const delta=r.reposicaoReal-r.sugestao;const note=delta>0?`O pedido ficou ${fmt(delta)} unidades acima da sugestão. Isso aumenta o estoque disponível e pode elevar o risco de produto vencer antes da venda.`:delta<0?`O pedido ficou ${fmt(Math.abs(delta))} unidades abaixo da sugestão. Vale confirmar se houve ruptura ou decisão comercial consciente.`:`Pedido e sugestão ficaram alinhados.`;els.drawerContent.innerHTML=`<div class="detail-grid"><div class="detail-card"><span>Estoque inicial</span><b>${fmt(r.estoqueAtual)}</b></div><div class="detail-card"><span>Vendas</span><b>${fmt(r.vendas)}</b></div><div class="detail-card"><span>Trocas</span><b>${fmt(r.trocas)}</b></div><div class="detail-card"><span>Taxa de trocas</span><b>${pct(r.taxaTrocas)}</b></div><div class="detail-card"><span>Sugestão</span><b>${fmt(r.sugestao)}</b></div><div class="detail-card"><span>Pedido realizado</span><b>${fmt(r.reposicaoReal)}</b></div><div class="detail-card"><span>Excesso</span><b>${fmt(r.excesso)}</b></div><div class="detail-card"><span>Estoque final</span><b>${fmt(r.estoqueFinal)}</b></div></div><div class="drawer-note ${r.risco==='ALTO'?'high':r.risco==='ATENÇÃO'?'attention':'normal'}"><b>Diagnóstico:</b> ${esc(note)}</div>`;els.drawer.classList.add('open');els.drawer.setAttribute('aria-hidden','false');els.drawerBack.classList.remove('hidden')}
function closeDrawer(){els.drawer.classList.remove('open');els.drawer.setAttribute('aria-hidden','true');els.drawerBack.classList.add('hidden')}
function setMode(live){els.liveBadge.classList.toggle('live',live);els.liveText.textContent=live?'LIVE':'DEMO';els.connectionDot.classList.toggle('live',live);els.connectionTitle.textContent=live?'Planilha conectada':'Modo demonstração';els.connectionSub.textContent=live?'Atualização via n8n':'Conecte o n8n para dados ao vivo'}
function openConnection(){const c=config();els.url.value=c.url;els.key.value=c.key;els.interval.value=String(c.interval);els.previewDot.className='';els.previewTitle.textContent=c.url?'Configuração salva':'Ainda não conectado';els.previewText.textContent=c.url?'Clique em Salvar e testar para validar agora.':'Cole a URL e clique em Salvar e testar.';els.modal.classList.remove('hidden')}
function closeConnection(){els.modal.classList.add('hidden')}
async function loadLive(show=false){const c=config();if(!c.url){dataset=window.DEMO_DASHBOARD_DATA;setMode(false);fillFilters();render();return false}try{if(show){els.previewTitle.textContent='Testando conexão...';els.previewText.textContent='Aguardando resposta do n8n.';els.previewDot.className=''}const headers={Accept:'application/json'};if(c.key)headers['x-dashboard-key']=c.key;const res=await fetch(c.url,{headers,cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const raw=await res.json();const rows=normalize(raw);if(!rows.length)throw new Error('A resposta não contém linhas válidas.');dataset={...raw,rows,updatedAt:raw.updatedAt||new Date().toISOString()};setMode(true);fillFilters();render();if(show){els.previewDot.className='ok';els.previewTitle.textContent='Conexão funcionando';els.previewText.textContent=`${rows.length} linhas recebidas do n8n.`}return true}catch(e){setMode(false);if(show){els.previewDot.className='error';els.previewTitle.textContent='Falha na conexão';els.previewText.textContent=e.message}else toast('Falha ao atualizar. Mantendo o último dado disponível.');return false}}
function restartTimer(){clearInterval(timer);const c=config();if(c.url)timer=setInterval(()=>loadLive(false),Math.max(15000,c.interval))}
function exportCsv(){const rows=selectedRows(),heads=['Cliente','Produto','Semana','Estoque Atual','Trocas','Vendas','Sugestão','Reposição Real','Estoque Final','Excesso','Status','Risco'];const body=rows.map(r=>[r.cliente,r.produto,r.semana,r.estoqueAtual,r.trocas,r.vendas,r.sugestao,r.reposicaoReal,r.estoqueFinal,r.excesso,r.status,r.risco]);const csv='\ufeff'+[heads,...body].map(a=>a.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='controle-reposicao.csv';a.click();URL.revokeObjectURL(a.href)}
function formatDate(v){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'medium'}).format(new Date(v))}catch{return '—'}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=({overview:'Visão geral',clients:'Clientes',products:'Produtos',alerts:'Alertas'})[name]||'Painel';$('#sidebar').classList.remove('open')}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));els.client.addEventListener('change',()=>{fillProducts();render()});els.product.addEventListener('change',render);els.status.addEventListener('change',render);$('#clientSearch').addEventListener('input',renderClients);$('#clientSort').addEventListener('change',renderClients);$('#productSearch').addEventListener('input',renderProducts);$('#productSort').addEventListener('change',renderProducts);$('#refreshBtn').addEventListener('click',()=>config().url?loadLive(false):render());$('#openConnectionBtn').addEventListener('click',openConnection);$('#closeConnectionBtn').addEventListener('click',closeConnection);els.modal.addEventListener('click',e=>{if(e.target===els.modal)closeConnection()});$('#saveConnectionBtn').addEventListener('click',async()=>{localStorage.setItem('rp_api_url',els.url.value.trim());localStorage.setItem('rp_api_key',els.key.value.trim());localStorage.setItem('rp_refresh',els.interval.value);const ok=await loadLive(true);if(ok){restartTimer();setTimeout(closeConnection,700)}});$('#demoModeBtn').addEventListener('click',()=>{localStorage.removeItem('rp_api_url');localStorage.removeItem('rp_api_key');clearInterval(timer);dataset=window.DEMO_DASHBOARD_DATA;setMode(false);fillFilters();render();els.previewDot.className='ok';els.previewTitle.textContent='Modo demonstração ativado';els.previewText.textContent='O painel voltou a usar os dados de exemplo.'});$('#exportBtn').addEventListener('click',exportCsv);$('#closeDrawerBtn').addEventListener('click',closeDrawer);els.drawerBack.addEventListener('click',closeDrawer);$('#mobileMenuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
fillFilters();render();setMode(false);if(config().url)loadLive(false).then(restartTimer);
})();
